### ISSUE TITLE
你的test.c中好像有一处bug

### ISSUE THREAD

**Issue by qinxiaobao8** [code-laoq/demo#2]
在第三行中，该语句的执行结果在xx情况下有误！

**Comment by code-laoq** [comment]
**感谢通知，我来排查下！**
![狗狗](https://user-images.githubusercontent.com/69424620/89750707-b1a33400-daff-11ea-9025-aa273fd30eb8.jpg)

**Comment by code-laoq** [comment]
的确如你所说，在输入数据为负数时，返回值出现了错误，我已经修复好了，你能帮我看下是否还有错误吗

**Comment by qinxiaobao8** [comment]
目前在你的项目中，我找不到任何错误
